### ISSUE TITLE
Question about the returned value of DFA

### ISSUE THREAD

**Issue by Alcampopiano** [CSchoel/nolds#12]
Hi Christopher,

Thanks very much for the nolds package.

I'm very new to DFA and I am trying to interpret the return value. I have seen others use DFA and report what they call an "exponent" that ranges from 0-1. 

For example, in [this Frontiers article](https://www.frontiersin.org/articles/10.3389/fphys.2012.00450/full) you can see the following figure that applies DFA to EEG. 

Do you happen to know how to get from the value that `nolds.dfa` returns, to this so-called "exponent"? It seems to be the slope within a selected window. I'm sure I'm missing something straightforward but I'm still trying to wrap my head around this measure.

![fphys-03-00450-g007](https://user-images.githubusercontent.com/4624246/54434982-da09e180-4705-11e9-8fb5-93c49f9bf17a.jpg)

**Comment by CSchoel** [comment]
I am very sorry, that I did not answer your question in time.
Since nolds is only a side project for me, I only occasionally check up on issues and mails.

For the record: The exponent you are looking for *is* the return value of `nolds.dfa`. In the documentation I do not call it "Hurst exponent" but "Hurst parameter" to distinguish it from the return value of `nolds.hurst_rs` (which has a similar but not identical interpretation) and to keep the terminology close to the literature. If you want to see/plot the line that is fitted, you can set the parameters `debug_plot` and `debug_data` to `True`.

The return value should be between 0 and 2 where values between 0 and 1 are obtained for stationary input data (mean and variance do not change when observing the data in windows) and values above 1 are an indication for non-stationary data. In the stationary case, the return value H is the "Hurst exponent", in the non-stationary case the "Hurst exponent" is H - 1.

**Comment by Alcampopiano** [comment]
Thanks Chris this is very helpful. Take care.
