### ISSUE TITLE
lyap_r for long time-series with many periods

### ISSUE THREAD

**Issue by jcvasquezc** [CSchoel/nolds#16]
The following warning checks for small frequencies in the estimation of lyap_r; and then assigns an arbitrary period based on the length of the time-series. 

This make the analysis dependent on the length of the signal. 

I have very long time series with a proper frequency, but which  get into the condition because the relationship with the length of the signal (gait time series from accelerometers).

How to take this into consideration?

https://github.com/CSchoel/nolds/blob/b52530a783d2d2aa39351ea285ab0d8e3a502ab3/nolds/measures.py#L237

**Comment by CSchoel** [comment]
Let me see... if I remember correctly, I implemented the warning to ensure that the calculated value of `min_tsep` would not be too large. The goal is to still find enough neighbors for each orbit vector. With `max_tsep_factor = 0.25` the condition that you mentioned ensures that half the orbit vectors will still be eligible as neighbors for the orbit vector that is right in the center of the time series (since `min_tsep` vectors to the right and `min_tsep` vectors to the left will not be eligible).

Can you tell me what the length and mean frequency of your data is? I don't think it should hit this warning unless the frequency is very low compared to the length of the data. If the default algorithm is an issue, you can always manually supply a value for `min_tsep`, which is probably favorable if you know the dominant frequency in your data beforehand, since it will make results more robust and more comparable across different time series.

**Comment by jcvasquezc** [comment]
Thank you 

The length of my time series is around 30000 samples, and the average frequency is around 100 samples, which is very low compared to the length, as you mention. Thus I have the described warning.

I will change the default parameters to match my conditions
