### ISSUE TITLE
lyap_r gives -inf 

### ISSUE THREAD

**Issue by mchandra** [CSchoel/nolds#19]
Hi,

I have a time series (data files attached below) that I suspect could be chaotic (plot below), and I'm trying to use nolds to compute its Lyapunov exponent. However, it gives me a -inf (with runtime warnings). Am I doing something silly here?

Code to produce the plot:
``` 
import numpy as np
time = np.loadtxt('times_for_test_time_series.txt')
signal = np.loadtxt('test_time_series.txt')

pl.plot(time, signal - np.mean(signal))
pl.ylabel("Voltage")
pl.xlabel("Time (ps)")
```

Code to compute Lyapunov exponent:
```
import nolds
nolds.lyap_r(signal)
```

![test](https://user-images.githubusercontent.com/527239/96371100-1dbc9c80-112e-11eb-8f89-36e90f12c95e.png)
[test_time_series.txt](https://github.com/CSchoel/nolds/files/5397643/test_time_series.txt)
[times_for_test_time_series.txt](https://github.com/CSchoel/nolds/files/5397645/times_for_test_time_series.txt)

**Comment by CSchoel** [comment]
I am sorry that it took me so long to answer. Since `lyap_r` works with logarithms of distances, a distance of zero can lead to a value of `-inf` in the algorithm. I would need some time to find out why this occurs for your particular data. If you have not already fixed this issue yourself and are still struggling with it, please let me know.

For nolds, I am considering to use this as an opportunity to add a few sentences to the return value documentation to explain the cases in which non-finite results can occur.

**Comment by CSchoel** [comment]
Ok, then I will have a look into your data when I find the time. I cannot say when this will be, but I will let you know if I find anything.

**Comment by CSchoel** [comment]
I guess I have to accept that I did not find the time to look into your data at all. Sorry. :disappointed: 

I'm closing this issue now. Let me know, if you still have issues with nolds and/or if you found a different implementation that worked better for your case.
