### ISSUE TITLE
emb_dim for sampen and corr_dim

### ISSUE THREAD

**Issue by DominiqueMakowski** [CSchoel/nolds#2]
I'm trying to compute the entropy and the fractal dimension of human physiological signals (EEG and ECG). However, I don't know on what basis to choose the  embedding dimension. Especially in `corr_dim` where emb_dim has no defaults. 

What defaults do you suggest? Or on what basis shoud we chose those values? Thanks!

**Comment by CSchoel** [comment]
Hi Dominique,

this is a good question and I wish I could give you a good answer. I implemented these algorithms in order to understand them myself. The correct choice of parameters still remains somewhat of a mystery to me and I think an arbitrary choice is a potential weakness of any analysis performed with these measures since you can often find a parameter set that shows what you want to show but is not necessarily a real effect in your data.

I actually use Nolds for the analysis of heart-rate variability data (series of RR-intervals) and I set the correlation dimention to 2 for both `sampen` and `corr_dim`, but this is totally arbitrary. I will have to come up with a plausible heuristic myself.

I would suggest that you turn to the literature and try to find other people that used the same measures with the same kind of data and hopefully report parameter settings (that hopefully are not also arbitrary :wink:). Another approach would be to use a set of sample data where you know that e.g. the Sample Entropy should be higher for dataset A than for dataset B. If you have enough data with preexisting diagnoses, you can try different parameter settings and select the one that gives the most plausible results on your sample data.

I will close this issue, since it is not an issue with the code but a question regarding the algorithms. If you want, you can contact me by email. You can find my [contatc information on my website](https://homepages.thm.de/~cslz90/).

Regards,
Christopher
