### ISSUE TITLE
Could I submit a PR that skips lag embedding for multivariate series

### ISSUE THREAD

**Issue by williamgilpin** [CSchoel/nolds#23]
Hello, I've been using a modified version of your code to calculate fractal dimension, lyapunov exponents, etc based on a custom embedding method. Would this be something valuable to include in the main repo? If so, I can put together a PR.

The basic structure is pretty simple: if the passed time series appears to be multivariate, then skip creating a lagged embedding. 

Thanks very much for this amazing library.

**Comment by CSchoel** [comment]
Hi, @williamgilpin . Thank you very much for your offer! :heart:  I would very much appreciate this pull request. I think this would also open up the algorithms to be used with multivariate data in general, not just with a custom embedding. I considered doing this myself for some time, but I currently have almost no time at all for developing nolds.

If you want to do this, I would be very glad if you could

* base your PR on the `dev` branch, since there is quite a bit of work currently sitting there that is almost finished and I would like to avoid conflicts with these changes.
* mention the option to pass multivariate data in the docstring of the algorithms (I think it would suffice to add a note to the main `data` parameter).
* and add a small test case in https://github.com/CSchoel/nolds/blob/dev/nolds/test_measures.py that uses the new feature.

I will check your PR as fast as I can, but as already mentioned I currently have very little time for nolds, since I am only a few months away from finishing my PhD thesis. So I apologize in advance if it should take longer.

**Comment by williamgilpin** [comment]
Great! I will start putting something together. I will make sure to base and periodically check the  `dev` branch to avoid any conflicts. Best of luck with finishing your PhD!!
