### ISSUE TITLE
Lyapunov exponent gave wrong result for Lorenz system

### ISSUE THREAD

**Issue by SMzubairshah** [CSchoel/nolds#24]
I use Lorenz system data for validation of the Rosenstein code but did not validate the results in Rosenstein's paper. can you explain how this nold is close to Rosenstein's paper results?

**Comment by CSchoel** [comment]
Hey, sorry for not answering for so long. I had a lot going on. :see_no_evil: 

If this is still relevant for you: There is a bit of example code on the current main branch that tests several algorithms on the Lorenz system in `nolds.examples`. You can run this with `python -m nolds.examples lorenz`. For me, this gives the following results:

```text
Expected Lyapunov exponent:  2.401312763583084
lyap_r(x)                 :  2.002617061985489
lyap_r(y)                 :  2.2350447381592535
lyap_r(z)                 :  2.0782816959701482
```

The expected value refers to this paper:

G. A. Leonov and N. V. Kuznetsov, “On differences and similarities in the analysis of Lorenz, Chen, and Lu systems,” Applied Mathematics and Computation, vol. 256, pp. 334–343, 2015, doi: 10.1016/j.amc.2014.12.132.

Since I assume that you probably have solved your issue in the last 3 months since you initially asked the question, I'll close this issue for now. Feel free to reopen it, however, if you still have any questions!
