### ISSUE TITLE
Citation for code

### ISSUE THREAD

**Issue by catubc** [CSchoel/nolds#7]
Hi Christopher.

I would like to use nolds for some neuroscience applications/papers and it looks very useful.

Do you have a published version of this package or the original measures that are implemented? Journals sometimes ask about peer reviewed toolboxes...

Thanks for this great package.
catubc

EDIT: I see the https://cschoel.github.io/nolds/ link that has more documentation and citations.

Q: Is nolds in process of publication as a toolbox?

**Comment by CSchoel** [comment]
Hi catubc,

Nolds is more of a side project for me. I need the code for my PhD thesis, but it is not the main focus of my research. Therefore I originally did not plan to turn it into a publication. However, as the package now grows and more people seem to find it useful, I am considering to change my mind on that. I will probably write a paper about Nolds in the future, but I cannot give any schedule for that, since I will have to do it in my spare time.

Until then I hope that it will help that most of the Algorithms have citations to the relevant literature in the documentation. For `hurst_rs` there are now some notes for a direct comparison to the R-Package Pracma and the Matlab implementation of Weron.

I will close this issue, but if you have any more questions feel free to contact me by mail (you can find my address on my [blog](http://arbitrary-but-fixed.net/)).
